#!/usr/bin/env python
"""Fine-tune LiquidAI/LFM2.5-Audio-1.5B on one voice, from a dataset the recorder exported. Any CUDA machine.

    pip install "liquid-audio==1.3.0" soundfile
    python finetune.py train --data voice-8f3a19c2 --name "Prannay"           # -> ckpt/Prannay/final + samples/
    python finetune.py say   --ckpt ckpt/Prannay/final --text "Hey, it's me." # -> say.wav

The dataset folder is what the recorder's "Download dataset" gives you, unzipped:
    voice-<slug>/clean/manifest.jsonl     one row per clip: {"file","text","duration_s","split"}
    voice-<slug>/clean/*.wav              24 kHz mono 16-bit, 1-14 s each

Steps inside `train`:
  1. tokenize   every clip -> Mimi audio tokens with Liquid's LFM2AudioChatMapper (a few minutes, GPU)
  2. fine-tune  liquid_audio.trainer.Trainer, full fine-tune (backbone, audio decoder, encoder, text embedder;
                the vocoder stays frozen), lr 5e-5, 10 % warmup, about 300 optimizer steps by default
  3. assemble   copy tokenizer/config/detokenizer next to the weights so `final/` loads with from_pretrained
  4. samples    four sentences rendered with the new voice -> <out>/samples/*.wav

Each training example is (system "Perform TTS. Use <Name>'s voice.", user <sentence>) -> your audio of that sentence.
There is no zero-shot cloning in this model: the name in the prompt is what the fine-tune teaches it to honor.

Hardware: 1.5B parameters, full fine-tune with AdamW -> about 40 GB of GPU memory at batch 16. An A100-80GB or
H100 is comfortable; on a 24 GB card use --batch 4. Ten minutes of audio is 5-15 minutes of A100 time.
"""
from __future__ import annotations

import argparse
import json
import math
import shutil
import sys
import time
from pathlib import Path

BASE_MODEL = "LiquidAI/LFM2.5-Audio-1.5B"
CONTEXT_LENGTH = 320
LR = 5e-5
FINAL_FILES = ("config.json", "tokenizer.json", "tokenizer_config.json", "special_tokens_map.json",
               "chat_template.jinja", "tokenizer-e351c8d8-checkpoint125.safetensors")


def system_prompt(name: str) -> str:
    return f"Perform TTS. Use {name}'s voice."


def sample_texts(name: str) -> list[str]:
    return [
        f"Hi, I'm {name}. This is my voice, generated by a model I fine-tuned on ten minutes of reading.",
        "The quick brown fox jumps over the lazy dog.",
        "Can you send me the deck before the meeting on Thursday? I want to read it on the train.",
        "We shipped it at four in the morning, and honestly, it just worked.",
    ]


def plan(n_train: int, batch: int | None, epochs: int | None, target_steps: int = 300) -> dict:
    """Small datasets need more epochs: aim for ~300 optimizer steps, 8-30 epochs, unless overridden."""
    b = batch or (16 if n_train >= 128 else 8 if n_train >= 32 else 4)
    steps_per_epoch = max(1, math.ceil(n_train / b))
    e = epochs or min(30, max(8, math.ceil(target_steps / steps_per_epoch)))
    return {"batch_size": b, "epochs": e, "steps_per_epoch": steps_per_epoch, "steps": steps_per_epoch * e}


def stamp(t0: float) -> str:
    m, s = divmod(int(time.time() - t0), 60)
    return f"[{m:02d}:{s:02d}]"


def read_manifest(clean: Path) -> list[dict]:
    path = clean / "manifest.jsonl"
    if not path.exists():
        sys.exit(f"{path} not found. Point --data at the unzipped dataset folder (it contains clean/manifest.jsonl).")
    rows = [json.loads(l) for l in path.read_text().splitlines() if l.strip()]
    missing = [r["file"] for r in rows if not (clean / r["file"]).exists()]
    if missing:
        sys.exit(f"{len(missing)} clips named in the manifest are missing, e.g. {missing[0]}")
    if sum(r.get("split") == "val" for r in rows) == 0 and len(rows) >= 10:
        for r in rows[:3]:
            r["split"] = "val"
    return rows


# --------------------------------------------------------------------------- train
def tokenize(rows: list[dict], clean: Path, out: Path, prompt: str, t0: float) -> dict:
    import torch
    from liquid_audio import LFM2AudioProcessor
    from liquid_audio.data.mapper import LFM2AudioChatMapper
    from liquid_audio.data.preprocess import preprocess_dataset
    from liquid_audio.data.types import AudioSegment, ChatMessage, TextSegment

    if out.exists():
        shutil.rmtree(out)
    processor = LFM2AudioProcessor.from_pretrained(BASE_MODEL, device="cuda").eval()
    mapper = LFM2AudioChatMapper(processor)
    print(f"{stamp(t0)} processor ready; {len(rows)} clips; prompt = {prompt!r}")

    class Messages:
        """Picklable iterable: `datasets` fingerprints the input with dill and cannot pickle a bare generator."""

        def __init__(self, split: str) -> None:
            self.rows = [r for r in rows if r.get("split", "train") == split]

        def __iter__(self):
            for r in self.rows:
                yield [
                    ChatMessage(role="system", content=[TextSegment(text=prompt)]),
                    ChatMessage(role="user", content=[TextSegment(text=r["text"])]),
                    ChatMessage(role="assistant", content=[AudioSegment(audio=(clean / r["file"]).read_bytes())]),
                ]

    counts = {}
    for split in ("train", "val"):
        n = sum(r.get("split", "train") == split for r in rows)
        if n == 0:
            counts[split] = 0
            continue
        with torch.no_grad():
            preprocess_dataset(data=Messages(split), output_path=out / split, mapper=mapper, max_context_length=CONTEXT_LENGTH)
        from datasets import load_from_disk
        counts[split] = len(load_from_disk(out / split))
        print(f"{stamp(t0)} {split}: {counts[split]}/{n} clips fit in {CONTEXT_LENGTH} tokens")
    del processor, mapper
    torch.cuda.empty_cache()
    return counts


def fine_tune(pre: Path, out: Path, counts: dict, p: dict, prompt: str, t0: float, max_steps: int) -> dict:
    from liquid_audio.data.dataloader import LFM2DataLoader
    from liquid_audio.trainer import Trainer
    from liquid_audio.utils import get_model_dir

    train_data = LFM2DataLoader(dataset_path=str(pre / "train"), context_length=CONTEXT_LENGTH)
    val_data = LFM2DataLoader(dataset_path=str(pre / "val"), context_length=CONTEXT_LENGTH) if counts.get("val") else None
    total = max_steps or p["steps"]
    warmup = max(5, int(0.1 * total))
    args = {"base_model": BASE_MODEL, "system_prompt": prompt, "n_train": counts["train"], "n_val": counts.get("val", 0),
            **p, "steps": total, "warmup": warmup, "lr": LR, "context_length": CONTEXT_LENGTH,
            "started": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())}
    out.mkdir(parents=True, exist_ok=True)
    (out / "training_args.json").write_text(json.dumps(args, indent=2))
    print(f"{stamp(t0)} fine-tune: {json.dumps(args)}")

    Trainer(
        model_id=BASE_MODEL, train_data=train_data, val_data=val_data, lr=LR, batch_size=p["batch_size"],
        max_steps=total, warmup_steps=warmup, dataloader_num_workers=4, logging_interval=5,
        save_interval=max(p["steps_per_epoch"] * 2, 50), val_interval=p["steps_per_epoch"], output_dir=str(out),
    ).train()

    final = out / "final"
    snap = get_model_dir(BASE_MODEL)
    for name in FINAL_FILES:
        if (snap / name).exists():
            shutil.copy(snap / name, final / name)
    if (snap / "audio_detokenizer").exists():
        shutil.copytree(snap / "audio_detokenizer", final / "audio_detokenizer", dirs_exist_ok=True)
    shutil.rmtree(out / "checkpoints", ignore_errors=True)  # optimizer states, ~12 GB each; final/ is what you keep
    args["finished"] = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
    args["train_minutes"] = round((time.time() - t0) / 60, 1)
    (out / "training_args.json").write_text(json.dumps(args, indent=2))
    print(f"{stamp(t0)} model at {final}")
    return args


# --------------------------------------------------------------------------- say
def load(ckpt: Path):
    from liquid_audio import LFM2AudioModel, LFM2AudioProcessor

    # a Path loads from disk; a str is treated as a Hugging Face repo id
    src = ckpt.resolve() if (ckpt / "model.safetensors").exists() else BASE_MODEL
    processor = LFM2AudioProcessor.from_pretrained(src, device="cuda").eval()
    model = LFM2AudioModel.from_pretrained(src, device="cuda").eval()
    return processor, model


def say(processor, model, prompt: str, text: str) -> "bytes":
    import io

    import soundfile as sf
    import torch
    from liquid_audio import ChatState

    chat = ChatState(processor)
    chat.new_turn("system"); chat.add_text(prompt); chat.end_turn()
    chat.new_turn("user"); chat.add_text(text); chat.end_turn()
    chat.new_turn("assistant")
    frames = []
    budget = min(1024, max(160, 40 * len(text.split())))
    for t in model.generate_sequential(**chat, max_new_tokens=budget, audio_temperature=0.8, audio_top_k=64):
        if t.numel() <= 1:
            continue
        if int(t[0]) == 2048:
            break
        frames.append(t)
    if not frames:
        raise RuntimeError(f"no audio generated for {text!r}")
    codes = torch.stack(frames, 1).unsqueeze(0).clamp(0, 2047)
    wav = processor.decode(codes).cpu()[0].float().numpy()
    buf = io.BytesIO()
    sf.write(buf, wav, 24_000, format="WAV", subtype="PCM_16")
    return buf.getvalue()


def prompt_for(ckpt: Path, name: str | None) -> str:
    if name:
        return system_prompt(name)
    args = ckpt.parent / "training_args.json"
    if args.exists():
        return json.loads(args.read_text())["system_prompt"]
    sys.exit("pass --name (the name you trained with) or keep training_args.json next to final/")


# --------------------------------------------------------------------------- cli
def cmd_train(a) -> None:
    import torch

    if not torch.cuda.is_available():
        sys.exit("no CUDA device: run this on a GPU machine (A100/H100 comfortable, 24 GB works with --batch 4)")
    t0 = time.time()
    data = Path(a.data)
    clean = data / "clean" if (data / "clean").exists() else data
    rows = read_manifest(clean)
    minutes = sum(float(r.get("duration_s", 0)) for r in rows) / 60
    print(f"{stamp(t0)} {len(rows)} clips, {minutes:.1f} min of audio, from {clean}")
    if minutes < 3 and not a.max_steps:
        print("warning: under 3 minutes of audio; expect a rough voice. Ten minutes is the practical minimum.")
    out = Path(a.out or f"ckpt/{a.name}")
    prompt = system_prompt(a.name)

    counts = tokenize(rows, clean, out / "preprocessed", prompt, t0)
    if counts["train"] < 4:
        sys.exit(f"only {counts['train']} training clips survived tokenization")
    p = plan(counts["train"], a.batch, a.epochs)
    args = fine_tune(out / "preprocessed", out, counts, p, prompt, t0, a.max_steps)
    shutil.rmtree(out / "preprocessed", ignore_errors=True)

    processor, model = load(out / "final")
    sdir = out / "samples"
    sdir.mkdir(exist_ok=True)
    for i, text in enumerate(sample_texts(a.name)):
        try:
            (sdir / f"{i:02d}.wav").write_bytes(say(processor, model, prompt, text))
            print(f"{stamp(t0)} sample {i}: {text}")
        except RuntimeError as e:
            print(f"{stamp(t0)} sample {i} skipped: {e}")
    print(f"\ndone in {args['train_minutes']} min. Model: {out / 'final'}   Samples: {sdir}")
    print(f'Next: python finetune.py say --ckpt {out / "final"} --text "Anything you like."')


def cmd_say(a) -> None:
    ckpt = Path(a.ckpt)
    prompt = prompt_for(ckpt, a.name)
    processor, model = load(ckpt)
    Path(a.out).write_bytes(say(processor, model, prompt, a.text))
    print(f"wrote {a.out}  ({prompt!r})")


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = p.add_subparsers(dest="cmd", required=True)
    t = sub.add_parser("train", help="tokenize + fine-tune + samples")
    t.add_argument("--data", required=True, help="unzipped dataset folder (has clean/manifest.jsonl)")
    t.add_argument("--name", required=True, help="the name in the prompt: Perform TTS. Use <name>'s voice.")
    t.add_argument("--out", help="output folder (default ckpt/<name>)")
    t.add_argument("--epochs", type=int, help="override the automatic schedule")
    t.add_argument("--batch", type=int, help="override the automatic batch size (4 on a 24 GB card)")
    t.add_argument("--max-steps", type=int, default=0, help="smoke test: stop after N optimizer steps")
    t.set_defaults(fn=cmd_train)
    s = sub.add_parser("say", help="render a sentence with a fine-tuned model")
    s.add_argument("--ckpt", required=True, help="the final/ folder")
    s.add_argument("--text", required=True)
    s.add_argument("--name", help="only if training_args.json is not next to final/")
    s.add_argument("--out", default="say.wav")
    s.set_defaults(fn=cmd_say)
    a = p.parse_args()
    a.fn(a)


if __name__ == "__main__":
    main()
