"""Voice Studio: record your voice in the browser, fine-tune LiquidAI/LFM2.5-Audio-1.5B on it, hear yourself.

One Modal app, one command:   uv run modal deploy studio.py      (or `make studio`)
Dev loop with live reload:    uv run modal serve  studio.py      (or `make studio-dev`)

Routes (all under the app's URL):
  GET  /                          landing page: start a new voice
  POST /api/new                   -> {slug, url}; the URL is the only key to that voice
  GET  /v/<slug>/                 the recorder (web/index.html)
  GET  /v/<slug>/train            the studio page: train, watch, listen (web/studio.html)
  *    /v/<slug>/api/...          state / take / skip (same contract as web/server.py), job, train, say
  GET  /v/<slug>/samples/<file>   wavs the finished run produced
  GET  /health

Storage on the shared volumes (see modal_app.py):
  voice-data  /data/<slug>/raw/       p####.wav + manifest.jsonl + skipped.json   (what the recorder writes)
              /data/<slug>/clean/     prepared 24 kHz clips                        (prepare.py, inside the pipeline)
              /data/<slug>/voice.json {slug, name, created}
              /data/<slug>/status.json pipeline phase log
  voice-ckpt  /ckpt/<slug>/final/     the fine-tuned model; /ckpt/<slug>/samples/*.wav

Settings, read from the deploying shell (put them in ~/.local/secrets or export before `make studio`):
  VOICE_STUDIO_CODES         comma-separated invite codes; when set, training needs one (each run costs GPU money)
  VOICE_STUDIO_ADMIN         one code that also allows smoke runs (max_steps) and bypasses the minimum audio
  VOICE_STUDIO_MIN_MINUTES   minutes of kept audio needed before Train unlocks (10)
  VOICE_STUDIO_TARGET_MINUTES what the recorder shows as the goal (30)
  VOICE_STUDIO_CONTACT       who to ask for a code, shown on the pages (e.g. an X handle)
  VOICE_STUDIO_REPO          link to the source, shown in the footer
"""
# No `from __future__ import annotations`: FastAPI needs real annotation objects on the handlers defined inside web().
import calendar
import json
import math
import os
import re
import secrets
import threading
import time
from pathlib import Path

import modal

from modal_app import CKPT, DATA, VOLUMES, app as train_app, ckpt_vol, data_vol, image, preprocess, synth, train

ROOT = Path(__file__).resolve().parent
APP = os.environ.get("VOICE_STUDIO_APP", "voice-studio")
SLUG_RE = re.compile(r"^[a-z0-9]{6,16}$")
MAX_BODY = 64 * 1024 * 1024
MAX_SAY_CHARS = 280
RUNNING = ("queued", "prepare", "preprocess", "train", "synth")

app = modal.App(APP)
app.include(train_app)

settings = modal.Secret.from_dict({
    k: os.environ.get(k, d) for k, d in {
        "VOICE_STUDIO_CODES": "",
        "VOICE_STUDIO_ADMIN": "",
        "VOICE_STUDIO_MIN_MINUTES": "10",
        "VOICE_STUDIO_TARGET_MINUTES": "30",
        "VOICE_STUDIO_CONTACT": "",
        "VOICE_STUDIO_REPO": "https://github.com/Pran-Ker/engram/tree/main/voice",
    }.items()
})

web_image = (
    modal.Image.debian_slim(python_version="3.12")
    .pip_install("fastapi[standard]>=0.115")
    .add_local_python_source("modal_app", "prepare", "takes")
    .add_local_file(ROOT / "prompts" / "sentences.txt", "/root/prompts/sentences.txt")
    .add_local_dir(ROOT / "web", remote_path="/root/web", ignore=["qa", "__pycache__", "*.py", "*.png"])
)


# --------------------------------------------------------------------------- shared helpers
def voice_dir(slug: str) -> Path:
    return DATA / slug


def read_json(path: Path, default):
    try:
        return json.loads(path.read_text())
    except (FileNotFoundError, json.JSONDecodeError):
        return default


def write_json(path: Path, obj) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(".tmp")
    tmp.write_text(json.dumps(obj, indent=2))
    os.replace(tmp, path)


def system_prompt(name: str) -> str:
    return f"Perform TTS. Use {name}'s voice."


def sample_texts(name: str) -> list[str]:
    return [
        f"Hi, I'm {name}. This is my voice, generated by a model I fine-tuned in my browser this afternoon.",
        "The quick brown fox jumps over the lazy dog.",
        "Can you send me the deck before the meeting on Thursday? I want to read it on the train.",
        "We shipped it at four in the morning, and honestly, it just worked.",
    ]


def plan(n_train: int, max_steps: int) -> dict:
    """Batch size and epochs for a dataset this small: aim for ~300 optimizer steps, 8-30 epochs."""
    batch = 16 if n_train >= 128 else 8 if n_train >= 32 else 4
    steps_per_epoch = max(1, math.ceil(n_train / batch))
    epochs = min(30, max(8, math.ceil(300 / steps_per_epoch)))
    return {"batch_size": batch, "epochs": epochs, "steps": max_steps or steps_per_epoch * epochs}


# --------------------------------------------------------------------------- pipeline
@app.function(image=image, volumes=VOLUMES, timeout=5 * 60 * 60, cpu=2, memory=4096)
def pipeline(slug: str, name: str, max_steps: int = 0) -> dict:
    """prepare (cpu, here) -> preprocess (L4) -> train (A100) -> synth (L4). Writes /data/<slug>/status.json as it goes."""
    from prepare import prepare

    t0 = time.time()
    status_path = voice_dir(slug) / "status.json"

    def status(phase: str, **kw) -> None:
        cur = read_json(status_path, {})
        cur.update(phase=phase, updated=time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
                   elapsed_s=round(time.time() - t0), **kw)
        write_json(status_path, cur)
        data_vol.commit()
        print(f"[{slug}] {phase} {json.dumps(kw)[:200]}", flush=True)

    try:
        status("prepare")
        data_vol.reload()
        stats = prepare(voice_dir(slug) / "raw", voice_dir(slug) / "clean")
        data_vol.commit()
        if stats["clips"] < 8:
            raise RuntimeError(f"only {stats['clips']} usable clips after cleanup (1-14 s each); record more")
        status("preprocess", clips=stats["clips"], minutes=stats["minutes"], dropped=len(stats["dropped"]))

        prompt = system_prompt(name)
        counts = preprocess.remote(slug, prompt, 320)
        n_train = int(counts.get("train", 0))
        if n_train < 4:
            raise RuntimeError(f"only {n_train} training samples survived tokenization")
        p = plan(n_train, max_steps)
        status("train", n_train=n_train, n_val=int(counts.get("val", 0)), **p)

        args = train.remote(slug, slug, p["epochs"], p["batch_size"], 5e-5, max_steps)
        status("synth", train_minutes=args.get("train_minutes"))

        texts = sample_texts(name)
        outs = synth.remote(slug, texts)
        samples = [{"file": fn, "text": texts[int(fn[:2])]} for fn, _ in outs]
        status("done", samples=samples, total_minutes=round((time.time() - t0) / 60, 1))
        return read_json(status_path, {})
    except Exception as e:
        status("error", error=f"{type(e).__name__}: {e}"[:600])
        raise


# --------------------------------------------------------------------------- speaker (interactive "say anything")
@app.cls(image=image, gpu="L4", volumes=VOLUMES, scaledown_window=300, timeout=600, startup_timeout=900)
class Speaker:
    @modal.enter()
    def setup(self):
        self.loaded: dict[str, tuple] = {}
        self.lock = threading.Lock()

    def _load(self, run: str):
        from liquid_audio import LFM2AudioModel, LFM2AudioProcessor

        if run not in self.loaded:
            ckpt_vol.reload()
            src = CKPT / run / "final"
            if not (src / "model.safetensors").exists():
                raise FileNotFoundError(f"no finished model for {run}")
            t0 = time.time()
            self.loaded[run] = (LFM2AudioProcessor.from_pretrained(src, device="cuda").eval(),
                                LFM2AudioModel.from_pretrained(src, device="cuda").eval())
            print(f"[speaker] loaded {run} in {time.time() - t0:.1f}s", flush=True)
        return self.loaded[run]

    @modal.method()
    def say(self, run: str, text: str, prompt: str) -> bytes:
        import io

        import soundfile as sf
        import torch
        from liquid_audio import ChatState

        with self.lock:
            processor, model = self._load(run)
            chat = ChatState(processor)
            chat.new_turn("system"); chat.add_text(prompt); chat.end_turn()
            chat.new_turn("user"); chat.add_text(text); chat.end_turn()
            chat.new_turn("assistant")
            frames = []
            budget = min(1024, max(160, 40 * len(text.split())))
            for t in model.generate_sequential(**chat, max_new_tokens=budget, audio_temperature=0.8, audio_top_k=64):
                if t.numel() <= 1:
                    continue
                if int(t[0]) == 2048:
                    break
                frames.append(t)
            if not frames:
                raise RuntimeError(f"no audio generated for {text!r}")
            codes = torch.stack(frames, 1).unsqueeze(0).clamp(0, 2047)
            wav = processor.decode(codes).cpu()[0].float().numpy()
        buf = io.BytesIO()
        sf.write(buf, wav, 24_000, format="WAV", subtype="PCM_16")
        return buf.getvalue()


# --------------------------------------------------------------------------- web
@app.function(image=web_image, volumes=VOLUMES, secrets=[settings], timeout=600, scaledown_window=900, max_containers=1)
@modal.concurrent(max_inputs=64)
@modal.asgi_app(label=APP)
def web():
    from fastapi import Body, FastAPI, HTTPException, Request
    from fastapi.responses import HTMLResponse, JSONResponse, RedirectResponse, Response
    from starlette.concurrency import run_in_threadpool

    from takes import BadRequest, Store, load_prompts

    web_dir = Path("/root/web")
    prompts = load_prompts(Path("/root/prompts/sentences.txt"))
    codes = {c.strip() for c in os.environ.get("VOICE_STUDIO_CODES", "").split(",") if c.strip()}
    admin = os.environ.get("VOICE_STUDIO_ADMIN", "").strip()
    min_minutes = float(os.environ.get("VOICE_STUDIO_MIN_MINUTES", "10"))
    target_minutes = float(os.environ.get("VOICE_STUDIO_TARGET_MINUTES", "30"))
    info = {
        "gated": bool(codes or admin),
        "min_minutes": min_minutes,
        "target_minutes": target_minutes,
        "contact": os.environ.get("VOICE_STUDIO_CONTACT", ""),
        "repo": os.environ.get("VOICE_STUDIO_REPO", ""),
    }
    stores: dict[str, Store] = {}
    stores_lock = threading.Lock()
    spawn_lock = threading.Lock()

    api = FastAPI(title="Voice Studio", docs_url=None, redoc_url=None)

    def page(name: str) -> HTMLResponse:
        return HTMLResponse((web_dir / name).read_text(), headers={"Cache-Control": "no-store"})

    def slug_ok(slug: str) -> str:
        if not SLUG_RE.match(slug) or not (voice_dir(slug) / "voice.json").exists():
            raise HTTPException(404, f"no voice {slug!r}: start one at /")
        return slug

    def store(slug: str) -> Store:
        with stores_lock:
            if slug not in stores:
                stores[slug] = Store(voice_dir(slug) / "raw", prompts, after_write=data_vol.commit)
            return stores[slug]

    def voice(slug: str) -> dict:
        return read_json(voice_dir(slug) / "voice.json", {"slug": slug, "name": ""})

    def refresh() -> None:
        """See what the pipeline container committed. Fails harmlessly while a take is being written."""
        try:
            data_vol.reload()
        except Exception as e:
            print(f"[volume] reload skipped: {e}", flush=True)

    def job(slug: str) -> dict:
        refresh()
        st = read_json(voice_dir(slug) / "status.json", {"phase": "none"})
        if st.get("phase") in RUNNING and st.get("updated"):
            # a pipeline that stopped reporting for 3 hours is dead (container lost); let the user retry
            age = time.time() - calendar.timegm(time.strptime(st["updated"], "%Y-%m-%dT%H:%M:%SZ"))
            if age > 3 * 3600:
                st = {**st, "phase": "error", "error": "the run stopped reporting; start it again"}
                write_json(voice_dir(slug) / "status.json", st)
                data_vol.commit()
        st["model_ready"] = (CKPT / slug / "final" / "model.safetensors").exists()
        return st

    async def body_of(req: Request) -> bytes:
        n = int(req.headers.get("content-length") or 0)
        if n > MAX_BODY:
            raise HTTPException(413, f"body {n} bytes exceeds {MAX_BODY}")
        return await req.body()

    @api.exception_handler(BadRequest)
    async def bad_request(_, e: BadRequest):
        return JSONResponse({"error": str(e)}, status_code=400)

    @api.exception_handler(HTTPException)
    async def http_error(_, e: HTTPException):
        return JSONResponse({"error": e.detail}, status_code=e.status_code)

    # ---- pages
    @api.get("/", response_class=HTMLResponse)
    def landing():
        return page("landing.html")

    @api.get("/health")
    def health():
        return {"ok": True, "app": APP, **info}

    @api.get("/api/info")
    def get_info():
        return info

    @api.post("/api/new")
    def new_voice():
        slug = secrets.token_hex(4)
        while (voice_dir(slug) / "voice.json").exists():
            slug = secrets.token_hex(4)
        write_json(voice_dir(slug) / "voice.json", {"slug": slug, "name": "", "created": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())})
        (voice_dir(slug) / "raw").mkdir(parents=True, exist_ok=True)
        data_vol.commit()
        return {"slug": slug, "url": f"/v/{slug}/"}

    @api.get("/v/{slug}", response_class=HTMLResponse)
    def recorder_noslash(slug: str):
        return RedirectResponse(f"/v/{slug_ok(slug)}/", status_code=307)

    @api.get("/v/{slug}/", response_class=HTMLResponse)
    def recorder(slug: str):
        slug_ok(slug)
        return page("index.html")

    @api.get("/v/{slug}/train", response_class=HTMLResponse)
    def studio(slug: str):
        slug_ok(slug)
        return page("studio.html")

    # ---- recorder api (same contract as web/server.py)
    @api.get("/v/{slug}/api/state")
    def state(slug: str):
        slug_ok(slug)
        return {**store(slug).state(), "studio": True, "voice": voice(slug), "job": job(slug), **info}

    @api.get("/v/{slug}/api/take/{idx}.wav")
    def take_wav(slug: str, idx: int):
        wav = store(slug_ok(slug)).take_bytes(idx)
        if wav is None:
            raise HTTPException(404, f"no take for prompt {idx}: record it first")
        return Response(wav, media_type="audio/wav", headers={"Cache-Control": "no-store"})

    @api.post("/v/{slug}/api/take/{idx}")
    async def put_take(slug: str, idx: int, req: Request, asr: str | None = None, mismatch: int = 0):
        slug_ok(slug)
        body = await body_of(req)
        if read_json(voice_dir(slug) / "status.json", {}).get("phase") in RUNNING:
            raise HTTPException(409, "training is running on these recordings; wait for it to finish")
        return await run_in_threadpool(store(slug).put_take, idx, body, asr, mismatch)

    @api.delete("/v/{slug}/api/take/{idx}")
    def delete_take(slug: str, idx: int):
        return store(slug_ok(slug)).delete_take(idx)

    @api.post("/v/{slug}/api/skip/{idx}")
    def skip(slug: str, idx: int, data: dict = Body(...)):
        slug_ok(slug)
        if not isinstance(data, dict) or not isinstance(data.get("skipped"), bool):
            raise BadRequest('missing boolean "skipped": send {"skipped": true|false}')
        return {"skipped": store(slug).set_skipped(idx, data["skipped"])}

    # ---- training
    @api.get("/v/{slug}/api/job")
    def get_job(slug: str):
        slug_ok(slug)
        st = store(slug).state()
        return {"job": job(slug), "voice": voice(slug), "count": st["count"], "minutes": round(st["total_seconds"] / 60, 2), **info}

    @api.post("/v/{slug}/api/train")
    def start_train(slug: str, data: dict = Body(...)):
        slug_ok(slug)
        name = re.sub(r"[^\w .'-]", "", str(data.get("name", ""))).strip()[:40]
        if len(name) < 2:
            raise BadRequest("give the voice a name (2-40 letters): it goes into the prompt the model is trained on")
        code = str(data.get("code", "")).strip()
        is_admin = bool(admin) and code == admin
        if info["gated"] and not (is_admin or code in codes):
            raise HTTPException(403, "training needs an invite code" + (f": ask {info['contact']}" if info["contact"] else ""))
        max_steps = int(data.get("max_steps", 0) or 0) if is_admin else 0
        minutes = store(slug).minutes()
        if minutes < min_minutes and not is_admin:
            raise BadRequest(f"{minutes:.1f} min recorded; the minimum is {min_minutes:g} min")
        with spawn_lock:
            if job(slug).get("phase") in RUNNING:
                raise HTTPException(409, "already training")
            v = {**voice(slug), "name": name}
            write_json(voice_dir(slug) / "voice.json", v)
            write_json(voice_dir(slug) / "status.json", {
                "phase": "queued", "name": name, "minutes": round(minutes, 2), "max_steps": max_steps,
                "started": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
                "updated": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()), "elapsed_s": 0,
            })
            data_vol.commit()
            call = pipeline.spawn(slug, name, max_steps)
            st = read_json(voice_dir(slug) / "status.json", {})
            st["call_id"] = call.object_id
            write_json(voice_dir(slug) / "status.json", st)
            data_vol.commit()
        return {"job": st}

    @api.get("/v/{slug}/samples/{name}")
    def sample(slug: str, name: str):
        slug_ok(slug)
        if not re.match(r"^[\w-]+\.wav$", name):
            raise HTTPException(404, "no such sample")
        path = CKPT / slug / "samples" / name
        if not path.exists():
            ckpt_vol.reload()
        if not path.exists():
            raise HTTPException(404, "no such sample")
        return Response(path.read_bytes(), media_type="audio/wav", headers={"Cache-Control": "public, max-age=3600"})

    @api.post("/v/{slug}/api/say")
    def say(slug: str, data: dict = Body(...)):
        slug_ok(slug)
        text = re.sub(r"\s+", " ", str(data.get("text", ""))).strip()
        if not text:
            raise BadRequest("text is empty")
        if len(text) > MAX_SAY_CHARS:
            raise BadRequest(f"text is {len(text)} chars; the limit is {MAX_SAY_CHARS}")
        if not job(slug).get("model_ready"):
            raise HTTPException(409, "this voice has not finished training")
        wav = Speaker().say.remote(slug, text, system_prompt(voice(slug).get("name") or "the speaker"))
        return Response(wav, media_type="audio/wav", headers={"Cache-Control": "no-store"})

    return api


# --------------------------------------------------------------------------- local helpers
if __name__ == "__main__":
    # `python studio.py url|status` talks to the deployed app without starting an ephemeral one.
    import sys

    action = sys.argv[1] if len(sys.argv) > 1 else "url"
    if action == "url":
        print(modal.Function.from_name(APP, "web").get_web_url())
    elif action == "status":
        print(modal.Function.from_name(APP, "check").remote())
    else:
        raise SystemExit("usage: python studio.py url|status")
